classdef UTestMgrs < matlab.unittest.TestCase

    properties (Constant)

        testLatitudeBands = struct( ...
            'letter', {'C','C','D','E','F','G','H','J','K','L','M','N','P','Q','R','S','T','U','V','W','X','X'}, ...
            'latitude_deg', {-85,-79,-71,-63,-55,-47,-39,-31,-23,-15,-7,1,9,17,25,33,41,49,57,65,73,85} )

        latitudeBandsBounds = struct( ...
            'letter', {'C','D','E','F','G','H','J','K','L','M','N','P','Q','R','S','T','U','V','W','X'}, ...
            'minLatBound', {-80,-72,-64,-56,-48,-40,-32,-24,-16,-8,0,8,16,24,32,40,48,56,64,72}, ...
            'maxLatBound', {-72,-64,-56,-48,-40,-32,-24,-16,-8,0,8,16,24,32,40,48,56,64,72,84} )

        longitudeZonesBounds = struct( ...
            'minLonBound', {-180,-174,-168,-162,-156,-150,-144,-138,-132,-126,-120,-114,-108,-102,-96,-90,-84,-78,-72,-66,-60,-54,-48,-42,-36,-30,-24,-18,-12,-6,0,6,12,18,24,30,36,42,48,54,60,66,72,78,84,90,96,102,108,114,120,126,132,138,144,150,156,162,168,174}, ...
            'maxLonBound', {-174,-168,-162,-156,-150,-144,-138,-132,-126,-120,-114,-108,-102,-96,-90,-84,-78,-72,-66,-60,-54,-48,-42,-36,-30,-24,-18,-12,-6,0,6,12,18,24,30,36,42,48,54,60,66,72,78,84,90,96,102,108,114,120,126,132,138,144,150,156,162,168,174,180} )

        testCoordinates = struct( ...
            'lat',  {0.0, 38.89012258965883, 60.389206862042705, -50.994763993878266}, ...
            'lon',  {0.0, -77.00902904474066, 5.319198457757746, -72.99966528495905}, ...
            'utm',  {"31N 166021 0000000", "18N 325758 4306501", "32N 297181 6700424", "18S 640372 4348852"}, ...
            'mgrs', {'31N AA 66021 00000', "18S UJ 25758 06501", "32V KN 97181 00424", "18F XJ 40372 48852"})

    end

    methods (Test)

        function testLatLonToUtmString(testCase)
            testData = testCase.testCoordinates;
            for ii = 1:numel(testData)
                testUtm = mgrs.UTM.fromLatLon(testData(ii).lat, testData(ii).lon);
                testCase.verifyMatches( ...
                    string(testUtm), ...
                    testData(ii).utm, ...
                    sprintf('Geolocation %f deg, %f deg converts to UTM string "%s" instead of the expected "%s".', ...
                    testData(ii).lat, testData(ii).lon, string(testUtm), testData(ii).utm) )
            end
        end

        function testUtmArrayToStrings(testCase)
            testData = testCase.testCoordinates;
            sizeTestData = size(testData);
            testUtmArray = mgrs.UTM.fromLatLon([testData.lat], [testData.lon]);
            testCase.verifySize( testUtmArray, sizeTestData, ...
                'mgrs.UTM.fromLatLon returned a UTM array of the wrong size.' )

            testCase.verifyClass( string(testUtmArray), 'string', ...
                'mgrs.UTM.fromLatLon did not return a string array when cast to string.' )
            testCase.verifySize( string(testUtmArray), sizeTestData, ...
                'mgrs.UTM.fromLatLon did not return a string array of the correct size')

            testCase.verifyTrue( iscellstr(cellstr(testUtmArray)), ...
                'mgrs.UTM.cellstr did not return a cell array of character vectors.')
        end

        function testGetBandLetter(testCase)
            testData = testCase.testLatitudeBands;
            for ii = 1:numel(testData)
                testCase.verifyMatches( ...
                    mgrs.gridZone.getBandLetter(testData(ii).latitude_deg), ...
                    testData(ii).letter, ...
                    sprintf('mgrs.gridZone.getBandLetter(%g) returns ''%s'' when it should return ''%s''.', ...
                    testData(ii).latitude_deg, mgrs.gridZone.getBandLetter(testData(ii).latitude_deg), testData(ii).letter) )
            end
        end

        function testBandBoundaries(testCase)
            testData = testCase.latitudeBandsBounds;
            for ii = 1:numel(testData)
                [actualMinLat_deg, actualMaxLat_deg] = mgrs.gridZone.getBandLimits(testData(ii).letter);

                % verify minimum latitude of band.
                testCase.verifyEqual( ...
                    actualMinLat_deg, testData(ii).minLatBound, ...
                    sprintf('mgrs.gridZone.getBandLimits(''%s'') returns %g deg for the minimum latitude, when %g deg is expected.', ...
                    testData(ii).letter, actualMinLat_deg, testData(ii).minLatBound) )

                % verify maximum latitude of band.
                testCase.verifyEqual( ...
                    actualMaxLat_deg, testData(ii).maxLatBound, ...
                    sprintf('mgrs.gridZone.getBandLimits(''%s'') returns %g deg for the maximum latitude, when %g deg is expected.', ...
                    testData(ii).letter, actualMaxLat_deg, testData(ii).maxLatBound) )
            end
        end

        function testVectorizedBandBoundaries(testCase)
            % This test exposes a bug in the original vectorized code which
            % fails to correct for the larger latitude height of band 'X',
            % when mgrs.gridZone.getBandLimits is called with a character
            % array instead of a scalar.
            testData = testCase.latitudeBandsBounds;
            [actualMinLat_deg, actualMaxLat_deg] = mgrs.gridZone.getBandLimits([testData(1).letter testData(end).letter]);

            % verify minimum latitude for band 'X'
            testCase.verifyEqual( ...
                actualMinLat_deg(end), testData(end).minLatBound, ...
                sprintf('mgrs.gridZone.getBandLimits(''%s'') returns %g deg for the minimum latitude, when %g deg is expected.', ...
                testData(end).letter, actualMinLat_deg(end), testData(end).minLatBound) )

            % verify maximum latitude for band 'X'
            testCase.verifyEqual( ...
                actualMaxLat_deg(end), testData(end).maxLatBound, ...
                sprintf('mgrs.gridZone.getBandLimits(''%s'') returns %g deg for the maximum latitude, when %g deg is expected.', ...
                testData(end).letter, actualMaxLat_deg(end), testData(end).maxLatBound) )
        end

        function testBandIncludesSouthBoundary(testCase)
            minLatBound_deg = mgrs.gridZone.getBandLimits('P');
            actualBandLetter = mgrs.gridZone.getBandLetter(minLatBound_deg);
            testCase.verifyMatches( ...
                actualBandLetter, 'P', ...
                'The southern boundary of the ''P'' band is not included in the ''P'' band, which is not consistent with the standard.' )
        end

        function testZoneBoundaries(testCase)
            testData = testCase.longitudeZonesBounds;
            for ii = 1:numel(testData)
                [actualMinLon_deg, actualMaxLon_deg] = mgrs.gridZone.getZoneLimits(ii);

                % verify minimum longitude of zone.
                testCase.verifyEqual( ...
                    actualMinLon_deg, testData(ii).minLonBound, ...
                    sprintf('mgrs.gridZone.getZoneLimits(%d) returns %g deg for the minimum longitude, when %g deg is expected.', ...
                    ii, actualMinLon_deg, testData(ii).minLonBound) )

                % verify maximum longitude of zone.
                testCase.verifyEqual( ...
                    actualMaxLon_deg, testData(ii).maxLonBound, ...
                    sprintf('mgrs.gridZone.getZoneLimits(%d) returns %g deg for the maximum longitude, when %g deg is expected.', ...
                    ii, actualMaxLon_deg, testData(ii).maxLonBound) )
            end
        end

    end

end